name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift 6.1
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1'

      - name: Build
        run: swift build

      - name: Test
        run: swift test
